workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        keystore: keystore.jks
        keystore_password: zohre9136431
        key_alias: parsa
        key_password: zohre9136431
    scripts:
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk